/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameHome;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.*;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author 63947
 */
public class homeMenu extends javax.swing.JFrame {

    /**
     * Creates new form DisOrDatMenu
     */
    Font watermelon;
    public homeMenu() {
        initComponents();
        setTitle("Quiz Games");
        /*try{
           watermelon = Font.createFont(Font.TRUETYPE_FONT, new File("Watermelon Days.ttf")).deriveFont(30f);
           GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
           ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Watermelon Days.ttf")));
        }catch(IOException | FontFormatException e){
            
        }*/
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        gameTitle = new javax.swing.JLabel();
        dordBtn = new javax.swing.JLabel();
        wtpkmnBtn = new javax.swing.JLabel();
        trivqBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        homePanel.setBackground(new java.awt.Color(73, 166, 166));

        gameTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/XenQuizzes_350x100.png"))); // NOI18N
        gameTitle.setFocusable(false);

        dordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BUTTONS_DORD_HOME.png"))); // NOI18N
        dordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dordBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dordBtnMouseExited(evt);
            }
        });

        wtpkmnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BUTTONS_PKMN_HOME.png"))); // NOI18N
        wtpkmnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wtpkmnBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wtpkmnBtnMouseExited(evt);
            }
        });

        trivqBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BUTTONS_TRIVQ_HOME.png"))); // NOI18N
        trivqBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trivqBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trivqBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(gameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wtpkmnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trivqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(gameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(wtpkmnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(trivqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dordBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dordBtnMouseEntered
        // TODO add your handling code here:
        Icon dord= new ImageIcon("D:\\63947\\Documents\\NetBeansProjects\\DisOrDat\\src\\assets\\BUTTONS_DORD_HOME_CYAN.png");
        dordBtn.setIcon(dord);
        dordBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dordBtnMouseEntered

    private void dordBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dordBtnMouseExited
        // TODO add your handling code here:
        Icon dord= new ImageIcon("D:\\63947\\Documents\\NetBeansProjects\\DisOrDat\\src\\assets\\BUTTONS_DORD_HOME.png");
        dordBtn.setIcon(dord);
    }//GEN-LAST:event_dordBtnMouseExited

    private void wtpkmnBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wtpkmnBtnMouseEntered
        // TODO add your handling code here:
        Icon wtpkmn= new ImageIcon("D:\\63947\\Documents\\NetBeansProjects\\DisOrDat\\src\\assets\\BUTTONS_PKMN_HOME_CYAN.png");
        wtpkmnBtn.setIcon(wtpkmn);
        dordBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_wtpkmnBtnMouseEntered

    private void wtpkmnBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wtpkmnBtnMouseExited
        // TODO add your handling code here:
        Icon wtpkmn= new ImageIcon("D:\\63947\\Documents\\NetBeansProjects\\DisOrDat\\src\\assets\\BUTTONS_PKMN_HOME.png");
        wtpkmnBtn.setIcon(wtpkmn);
    }//GEN-LAST:event_wtpkmnBtnMouseExited

    private void trivqBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trivqBtnMouseEntered
        // TODO add your handling code here:
        Icon trivq = new ImageIcon("D:\\63947\\Documents\\NetBeansProjects\\DisOrDat\\src\\assets\\BUTTONS_TRIVQ_HOME_CYAN.png");
        trivqBtn.setIcon(trivq);
        dordBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_trivqBtnMouseEntered

    private void trivqBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trivqBtnMouseExited
        // TODO add your handling code here:
        Icon trivq = new ImageIcon("D:\\63947\\Documents\\NetBeansProjects\\DisOrDat\\src\\assets\\BUTTONS_TRIVQ_HOME.png");
        trivqBtn.setIcon(trivq);
    }//GEN-LAST:event_trivqBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dordBtn;
    private javax.swing.JLabel gameTitle;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel trivqBtn;
    private javax.swing.JLabel wtpkmnBtn;
    // End of variables declaration//GEN-END:variables
}
